/*
 * Medication Management API
 *
 * Medication management for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: ladaivanna.matveeva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package medication

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type MedicationListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateMedicationListEntry - Saves new entry into medication list
   CreateMedicationListEntry(ctx *gin.Context)

    // DeleteMedicationListEntry - Deletes a specific medication
   DeleteMedicationListEntry(ctx *gin.Context)

    // GetMedicationListEntries - Provides the ambulance medication list
   GetMedicationListEntries(ctx *gin.Context)

    // GetMedicationListEntry - Provides details about a specific medication
   GetMedicationListEntry(ctx *gin.Context)

    // UpdateMedicationListEntry - Updates specific medication details
   UpdateMedicationListEntry(ctx *gin.Context)

 }

// partial implementation of MedicationListAPI - all functions must be implemented in add on files
type implMedicationListAPI struct {

}

func newMedicationListAPI() MedicationListAPI {
  return &implMedicationListAPI{}
}

func (this *implMedicationListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/medication-list/:ambulanceId/entries", this.CreateMedicationListEntry)
  routerGroup.Handle( http.MethodDelete, "/medication-list/:ambulanceId/entries/:entryId", this.DeleteMedicationListEntry)
  routerGroup.Handle( http.MethodGet, "/medication-list/:ambulanceId/entries", this.GetMedicationListEntries)
  routerGroup.Handle( http.MethodGet, "/medication-list/:ambulanceId/entries/:entryId", this.GetMedicationListEntry)
  routerGroup.Handle( http.MethodPut, "/medication-list/:ambulanceId/entries/:entryId", this.UpdateMedicationListEntry)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateMedicationListEntry - Saves new entry into medication list
// func (this *implMedicationListAPI) CreateMedicationListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteMedicationListEntry - Deletes a specific medication
// func (this *implMedicationListAPI) DeleteMedicationListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMedicationListEntries - Provides the ambulance medication list
// func (this *implMedicationListAPI) GetMedicationListEntries(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMedicationListEntry - Provides details about a specific medication
// func (this *implMedicationListAPI) GetMedicationListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateMedicationListEntry - Updates specific medication details
// func (this *implMedicationListAPI) UpdateMedicationListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

