/*
 * Medication Management API
 *
 * Medication management for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: ladaivanna.matveeva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medication

type MedicationListEntry struct {

	// Unique id of the entry in this medication list
	Id string `json:"id"`

	// Name of medication in medication list
	Name string `json:"name"`

	// Dosage of the medication per intake
	Dosage string `json:"dosage"`

	// How many times the medication should be taken per day
	FrequencyPerDay int32 `json:"frequencyPerDay"`

	// Expiration date of the medication
	ExpirationDate string `json:"expirationDate,omitempty"`
}
