/*
 * Medication Management API
 *
 * Medication management for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: ladaivanna.matveeva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medication

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newMedicationListAPI()
    api.addRoutes(group)
  }
  
}